### PR TITLE
Update to Rails 6

### PR DESCRIPTION
**Pull request by AJMiller**
[Pivotal Chore](https://www.pivotaltracker.com/story/show/172559396)

Update our interview repo to Rails 6

### CODE REVIEW

**Comment by AJMiller** [comment]
- Removed turbolinks and coffeescript
  - we wouldn't expect candidates to use these 
- Removed version constraints
  - This is a simple repo. Should be able to just run `bundle update` and not worry about versions

**Review by bmack123 — CHANGES_REQUESTED** [review]
This all looks good to me, but should we look at upgrading to node 12 as well? Just so that way we don't have to remember to switch nodes, I doubt most of us run the command to do `nvm use` on folder change if necessary.

**Comment by AJMiller** [comment]
I can do that in a separate PR. My hope was to keep this one constrained to Rails. That way if something breaks we don't have two things to check.

**Review by bmack123 — APPROVED** [review]
LGTM

**Comment by bmack123** [comment]
Acceptance Testing
---
- [x] I can still run the rails and client server
- [x] The interview repo still functions

🉑

**Pull request merged**
